name: Build cli

on:
  pull_request:
    branches:
      - main
    paths:
      - cmd/cli/**
      - internal/**
      - go.mod
      - go.sum
      - justfile
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-cli:
    name: Build cli
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Build cli
        run: just build-cli
