name: Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
    build-backend-amd64:
        name: build backend
        runs-on: ubuntu-24.04
        outputs:
            digest: ${{ steps.build.outputs.digest }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v4
              with:
                registry: ${{ env.CONTAINER_REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Build and push
              id: build
              uses: docker/build-push-action@v7
              with:
                push: ${{ github.event_name == 'push' }} # Only push the image if we're on main
                platforms: linux/amd64
                outputs: type=image,name=${{ env.CONTAINER_REGISTRY }}/do-2k25-28/push-n-pray,push-by-digest=true,name-canonical=true
                cache-from: type=gha,scope=buildkit-amd64
                cache-to: type=gha,mode=max,scope=buildkit-amd64

    build-backend-arm64:
        name: Build arm64 image
        runs-on: ubuntu-24.04-arm
        outputs:
            digest: ${{ steps.build.outputs.digest }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v4
              with:
                registry: ${{ env.CONTAINER_REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Build and push
              id: build
              uses: docker/build-push-action@v7
              with:
                push: ${{ github.event_name == 'push' }} # Only push the image if we're on main
                platforms: linux/arm64
                outputs: type=image,name=${{ env.CONTAINER_REGISTRY }}/do-2k25-28/push-n-pray,push-by-digest=true,name-canonical=true
                cache-from: type=gha,scope=buildkit-arm64
                cache-to: type=gha,mode=max,scope=buildkit-arm64

    merge-manifest:
        name: Merge multi-arch image
        runs-on: ubuntu-24.04
        needs:
            - build-backend-amd64
            - build-backend-arm64
        if: github.event_name == 'push'
        steps:
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v4
              with:
                registry: ${{ env.CONTAINER_REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Create and push manifest
              run: >-
                docker buildx imagetools create -t ${{ env.CONTAINER_REGISTRY }}/do-2k25-28/push-n-pray:${{ github.sha }}
                ${{ env.CONTAINER_REGISTRY }}/do-2k25-28/push-n-pray@${{ needs.build-backend-amd64.outputs.digest }}
                ${{ env.CONTAINER_REGISTRY }}/do-2k25-28/push-n-pray@${{ needs.build-backend-arm64.outputs.digest }}
