name: Code quality

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
