name: Code quality

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install ToolChain
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  go-fmt:
    name: Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install tool chain
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Go format
        run: find . -name go.mod -not -path './.git/*' -execdir sh -c 'test -z "$(gofmt -l .)"' \;

  go-vet:
    name: Vet
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install tool chain
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Run go vet
        run: find . -name go.mod -not -path './.git/*' -execdir go vet ./... \;
